### ISSUE TITLE
Switching to shooting range issue

### ISSUE THREAD

**Issue by DinoNuggets2** [rayzerbrain/Spectator-Shooting-Range#1]
Whenever I type the .range command as a spectator, is says in the console a huge error. I am not sure why.

**Comment by rayzerbrain** [comment]
Can you show me what it looks like

**Comment by DinoNuggets2** [comment]
Here.

![Screenshot (79)](https://user-images.githubusercontent.com/91291118/134755126-4f6fe038-6635-4c0e-82b2-947d607e842e.png)

**Comment by rayzerbrain** [comment]
try the new build i released and see if it has the same issue. (if it has a different message send that too)

**Comment by DinoNuggets2** [comment]
Still doing the same thing.

Duplicate of #

**Comment by rayzerbrain** [comment]
Do you know what version of exiled you are currently using?

**Comment by DinoNuggets2** [comment]
When a new round starts, this is what comes out of the logs. (It comes out red)

Exiled.Loader - Version 2.14.0

Duplicate of #

**Comment by rayzerbrain** [comment]
Sorry this plugin only works with version 3.0 of exiled, which is for the public beta of the 11.0 version of sl. If you want to update your server to the beta(which i recommend, it has cool stuff), the official sl discord has a server-faq channel that tells you how. (if you have any other issues you can make a new thread)

**Comment by DinoNuggets2** [comment]
Okay, thanks.
