### ISSUE TITLE
Auto kill before respawns

### ISSUE THREAD

**Issue by DinoNuggets2** [rayzerbrain/Spectator-Shooting-Range#10]
About 30 seconds before a respawn when players would normally be killed, they don't get killed at all before a respawn.

**Comment by rayzerbrain** [comment]
redownload the dll real quick and see if that works

**Comment by DinoNuggets2** [comment]
No, it still won't work

**Comment by rayzerbrain** [comment]
It works for me, so it must be something on your end.
Do you have any errors or logs? Also does the broadcast message show up or no when this happens

**Comment by DinoNuggets2** [comment]
When I am testing it with multiple people, it only happens to me.

**Comment by DinoNuggets2** [comment]
Actually, it only kills one player before a respawn.

**Comment by rayzerbrain** [comment]
odd

**Comment by rayzerbrain** [comment]
Ok i think I isolated the issue, check the releases and tell me if it works

**Comment by DinoNuggets2** [comment]
It works, thanks.

**Comment by rayzerbrain** [comment]
np
