### ISSUE TITLE
best spawn suggestion

### ISSUE THREAD

**Issue by Galinhadofuturo** [rayzerbrain/Spectator-Shooting-Range#13]
instead of the plugin taking you out of the shooting range and putting the player in the last few seconds when they are about to spawn. When spectators spawn the sniper would also spawn without having the plugin need to take the sniper to spectator mode. Reason: it's not difficult to get back into sniper mode even with 15 seconds left to appear, thus bypassing the spawn.
(possibly it must be difficult to understand my english. sorry he is horrible).

**Comment by rayzerbrain** [comment]
New version fixes this too
