### ISSUE TITLE
What permission

### ISSUE THREAD

**Issue by Galinhadofuturo** [rayzerbrain/Spectator-Shooting-Range#14]
What permission is needed for players to use .range?

**Comment by Wafelowski** [comment]
There's no permission, but there are requirements:
- Player must be a spectator
- Round must be started
- Player must have died since the round started

**Comment by Galinhadofuturo** [comment]
yes, the player is apparently following the requirements, but regardless of that, the console keeps saying that the player is not allowed to do so
error: (https://media.discordapp.net/attachments/710353076590215238/961022540153761862/unknown.png)

**Comment by Galinhadofuturo** [comment]
[](https://media.discordapp.net/attachments/710353076590215238/961022540153761862/unknown.png)

**Comment by rayzerbrain** [comment]
new version fixes this
