### ISSUE TITLE
Enter the shooting range, the model becomes smaller, hit the target and deviate

### ISSUE THREAD

**Issue by 1462903025** [rayzerbrain/Spectator-Shooting-Range#15]
Enter the shooting range, the model becomes smaller, hit the target and deviate

**Comment by 1462903025** [comment]
I aimed at the head and actually hit the stomach
<a href="https://imgtu.com/i/XJxEsP"><img src="https://s1.ax1x.com/2022/06/01/XJxEsP.png" alt="XJxEsP.png" border="0" /></a>
Player size
<a href="https://imgtu.com/i/XJxMGj"><img src="https://s1.ax1x.com/2022/06/01/XJxMGj.md.png" alt="XJxMGj.png" border="0" /></a>

**Comment by rayzerbrain** [comment]
Cause unknown, please try disabling other plugins and see if that fixes anything.

**Comment by 1462903025** [comment]
I successfully fixed it with version 3.0.0
<a href="https://imgtu.com/i/XtzZXn"><img src="https://s1.ax1x.com/2022/06/02/XtzZXn.png" alt="XtzZXn.png" border="0" /></a>https://github.com/1462903025/ShootingRange
