### ISSUE TITLE
Boundries Dont Work

### ISSUE THREAD

**Issue by DinoNuggets2** [rayzerbrain/Spectator-Shooting-Range#2]
When someone tries to jump out of the shooting range, they don't die. Instead, they are stuck in the void unless they rejoin. They can also walk right out to the escape area and shoot people escaping and at Gate B

**Comment by rayzerbrain** [comment]
If this happened due to you using a newer version, use the one that was working before, or any other version. i'll try to fix it sometime tomorrow

**Comment by rayzerbrain** [comment]
Turned out to be an exiled issue. It should work with the latest version
