### ISSUE TITLE
People randomly getting killed with the reason " went out of bounds" 

### ISSUE THREAD

**Issue by DinoNuggets2** [rayzerbrain/Spectator-Shooting-Range#4]
Randomly people will get killed walking through the facility with the reason "Went out of bounds"

**Comment by rayzerbrain** [comment]
can you send me a picture of this happening

**Comment by rayzerbrain** [comment]
also is this happening for people that aren't tutorial class

**Comment by DinoNuggets2** [comment]
Yes. I cant get a screenshot because I can't run into it, but it mostly happens to guards. I think the boundaries go down to the facility map from the surface.

**Comment by rayzerbrain** [comment]
I'll do some reworking soon
