### ISSUE TITLE
Floor collisions enabled (11.1.1)

### ISSUE THREAD

**Issue by DinoNuggets2** [rayzerbrain/Spectator-Shooting-Range#7]
11.1.1 made the floor at the shooting range collidable, so people just fall through and never stop falling. Might need to make a floor with primitives or something else if you use map editor since the normal ground is collidable now.

**Comment by rayzerbrain** [comment]
ugh why would they do that... 

Well i don't have much experience with making unity objects but i'll try my best. Might have to wait till I finish some other stuff

**Comment by DinoNuggets2** [comment]
Exactly, I don't understand why they did that. I have experience with MapEditorReborn, but I have no idea how to use it with plugins and stuff

**Comment by rayzerbrain** [comment]
Yeah, it also makes it a little more confusing when my plugin is dependent upon another, I'll find some way to add it myself
