### ISSUE TITLE
Spawn Suggestion

### ISSUE THREAD

**Issue by DinoNuggets2** [rayzerbrain/Spectator-Shooting-Range#8]
Allow a config to set a specific coordinate to teleport to once a player types .range in their console. Also as an extra suggestion too, allow multiple spawn coordinates to be put in the config, and one random one is chosen when someone types .range . This way if server owners build their own shooting range as well, it will send the player to either the specified coordinate, or the shooting range that came with the plugin.

I know this is a little confusing, if you have questions DM me, DinoNuggets2#7163, I am in the EXILED discord.

**Comment by rayzerbrain** [comment]
just released new version (it's in pre-releases)
